apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: host-info
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: host-info
          servicePort: 8080
